# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

steps:
  - label: "New Beta Release"
    plugins: [$CI_TOOLKIT]
    command: |
      source .buildkite/commands/configure-for-release.sh

      echo '--- :git: Checkout Release Branch'
      .buildkite/commands/checkout-release-branch.sh

      echo '--- :shipit: New Beta Release'
      bundle exec fastlane new_beta_release skip_confirm:true include_wear_app:"${INCLUDE_WEAR_APP:-false}"
    agents:
        queue: "tumblr-metal"
