agents:
  queue: "android"

steps:
  - label: " Start Code Freeze"
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
    command: |
      .buildkite/commands/configure-environment.sh

      echo '--- :snowflake: Start Code Freeze'
      bundle exec fastlane start_code_freeze skip_confirm:true
