# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: " Start Code Freeze"
    plugins: [$CI_TOOLKIT]
    command: |
      .buildkite/commands/configure-environment.sh

      echo '--- :snowflake: Start Code Freeze'
      bundle exec fastlane start_code_freeze skip_confirm:true
